package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseAgenda;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agenda extends BaseAgenda<Agenda> {
	public static final Agenda dao = new Agenda().dao();
}

