package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseCollage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collage extends BaseCollage<Collage> {
	public static final Collage dao = new Collage().dao();
}

