package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseCompetition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Competition extends BaseCompetition<Competition> {
	public static final Competition dao = new Competition().dao();
}

