package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member().dao();
}

