package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource().dao();
}

