package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
	public static final RoleMenu dao = new RoleMenu().dao();
}

