package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseSubset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subset extends BaseSubset<Subset> {
	public static final Subset dao = new Subset().dao();
}

