package org.project.agenda.common.module;

import org.project.agenda.common.module.base.BaseUserMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMenu extends BaseUserMenu<UserMenu> {
	public static final UserMenu dao = new UserMenu().dao();
}

