package org.project.agenda.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserSession<M extends BaseUserSession<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 用户ID 对应user表id
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID 对应user表id
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * sessionID 用于表示session,即token
	 */
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}
	
	/**
	 * sessionID 用于表示session,即token
	 */
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}
	
	/**
	 * session有效时间 单位s，0表示永久有效
	 */
	public void setExpiresIn(java.lang.Long expiresIn) {
		set("expires_in", expiresIn);
	}
	
	/**
	 * session有效时间 单位s，0表示永久有效
	 */
	public java.lang.Long getExpiresIn() {
		return getLong("expires_in");
	}
	
	/**
	 * session过期时间 0表示永久有效，否则为session过期时间
	 */
	public void setExpiresTime(java.lang.Long expiresTime) {
		set("expires_time", expiresTime);
	}
	
	/**
	 * session过期时间 0表示永久有效，否则为session过期时间
	 */
	public java.lang.Long getExpiresTime() {
		return getLong("expires_time");
	}
	
}

