package org.project.agenda.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAgenda<M extends BaseAgenda<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 用户id
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 学年 某一学年
	 */
	public void setYear(java.lang.Integer year) {
		set("year", year);
	}
	
	/**
	 * 学年 某一学年
	 */
	public java.lang.Integer getYear() {
		return getInt("year");
	}
	
	/**
	 * 学期 某一学期,1-上学期 2-下学期
	 */
	public void setTerm(java.lang.Integer term) {
		set("term", term);
	}
	
	/**
	 * 学期 某一学期,1-上学期 2-下学期
	 */
	public java.lang.Integer getTerm() {
		return getInt("term");
	}
	
	/**
	 * 周次 参考学校教学周,例如8表示第八周,寒暑假不考虑,因为基本都有空
	 */
	public void setWeek(java.lang.Integer week) {
		set("week", week);
	}
	
	/**
	 * 周次 参考学校教学周,例如8表示第八周,寒暑假不考虑,因为基本都有空
	 */
	public java.lang.Integer getWeek() {
		return getInt("week");
	}
	
	/**
	 * 周几 表示周几,例如1表示周一
	 */
	public void setDay(java.lang.Integer day) {
		set("day", day);
	}
	
	/**
	 * 周几 表示周几,例如1表示周一
	 */
	public java.lang.Integer getDay() {
		return getInt("day");
	}
	
	/**
	 * 日程名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 日程名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 起始时间
	 */
	public void setBegin(java.lang.String begin) {
		set("begin", begin);
	}
	
	/**
	 * 起始时间
	 */
	public java.lang.String getBegin() {
		return getStr("begin");
	}
	
	/**
	 * 结束时间
	 */
	public void setEnd(java.lang.String end) {
		set("end", end);
	}
	
	/**
	 * 结束时间
	 */
	public java.lang.String getEnd() {
		return getStr("end");
	}
	
	/**
	 * 是否提醒 1-不提醒 2-提醒
	 */
	public void setIsRemind(java.lang.Integer isRemind) {
		set("is_remind", isRemind);
	}
	
	/**
	 * 是否提醒 1-不提醒 2-提醒
	 */
	public java.lang.Integer getIsRemind() {
		return getInt("is_remind");
	}
	
	/**
	 * 提醒时间 根据起始时间-设定的提醒得到提醒时间,用于到点发邮件提醒
	 */
	public void setRemind(java.lang.String remind) {
		set("remind", remind);
	}
	
	/**
	 * 提醒时间 根据起始时间-设定的提醒得到提醒时间,用于到点发邮件提醒
	 */
	public java.lang.String getRemind() {
		return getStr("remind");
	}
	
	/**
	 * 提醒方式 1-邮件 2-短信 3-企业微信等
	 */
	public void setWay(java.lang.Integer way) {
		set("way", way);
	}
	
	/**
	 * 提醒方式 1-邮件 2-短信 3-企业微信等
	 */
	public java.lang.Integer getWay() {
		return getInt("way");
	}
	
	/**
	 * 日程地点 上课开会的地点等
	 */
	public void setPlace(java.lang.String place) {
		set("place", place);
	}
	
	/**
	 * 日程地点 上课开会的地点等
	 */
	public java.lang.String getPlace() {
		return getStr("place");
	}
	
	/**
	 * 举办者 例如上课的教师,开会的主持人等
	 */
	public void setOrganizers(java.lang.String organizers) {
		set("organizers", organizers);
	}
	
	/**
	 * 举办者 例如上课的教师,开会的主持人等
	 */
	public java.lang.String getOrganizers() {
		return getStr("organizers");
	}
	
	/**
	 * 备注 一些上课开会的备注消息,例如开会时要带电脑,上课要点名,这节课的任务等等
	 */
	public void setInformation(java.lang.String information) {
		set("information", information);
	}
	
	/**
	 * 备注 一些上课开会的备注消息,例如开会时要带电脑,上课要点名,这节课的任务等等
	 */
	public java.lang.String getInformation() {
		return getStr("information");
	}
	
}

