package org.project.agenda.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 账号 普通用户-学号 管理员-自定义账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账号 普通用户-学号 管理员-自定义账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 密码 加密后的密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码 加密后的密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 加密盐 添加用户时生成
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 加密盐 添加用户时生成
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 姓名 管理员导入
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名 管理员导入
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 学号 管理员导入
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 学号 管理员导入
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 性别 0-女 1-男
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 性别 0-女 1-男
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}
	
	/**
	 * 学院 学院id
	 */
	public void setCollageId(java.math.BigInteger collageId) {
		set("collage_id", collageId);
	}
	
	/**
	 * 学院 学院id
	 */
	public java.math.BigInteger getCollageId() {
		return get("collage_id");
	}
	
	/**
	 * 班级 班级名称,由用户直接输入,自行决定
	 */
	public void setClasses(java.lang.String classes) {
		set("classes", classes);
	}
	
	/**
	 * 班级 班级名称,由用户直接输入,自行决定
	 */
	public java.lang.String getClasses() {
		return getStr("classes");
	}
	
	/**
	 * 邮箱 邮箱,便于发提醒消息
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱 邮箱,便于发提醒消息
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 头像 指向file中的一个头像文件
	 */
	public void setFileId(java.math.BigInteger fileId) {
		set("file_id", fileId);
	}
	
	/**
	 * 头像 指向file中的一个头像文件
	 */
	public java.math.BigInteger getFileId() {
		return get("file_id");
	}
	
	/**
	 * 手机号 手机号,便于联系,也可以发短信提醒
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号 手机号,便于联系,也可以发短信提醒
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 简介 简介信息,供他人查看,便于组队,可以存1000多个汉字
	 */
	public void setInformation(java.lang.String information) {
		set("information", information);
	}
	
	/**
	 * 简介 简介信息,供他人查看,便于组队,可以存1000多个汉字
	 */
	public java.lang.String getInformation() {
		return getStr("information");
	}
	
}

