package org.project.agenda.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 资料名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 资料名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 资料链接 可以是网页资源链接等形式
	 */
	public void setLink(java.lang.String link) {
		set("link", link);
	}
	
	/**
	 * 资料链接 可以是网页资源链接等形式
	 */
	public java.lang.String getLink() {
		return getStr("link");
	}
	
	/**
	 * 资料文件 上传的视频等文件id
	 */
	public void setFileId(java.math.BigInteger fileId) {
		set("file_id", fileId);
	}
	
	/**
	 * 资料文件 上传的视频等文件id
	 */
	public java.math.BigInteger getFileId() {
		return get("file_id");
	}
	
	/**
	 * 资料介绍
	 */
	public void setInformation(java.lang.String information) {
		set("information", information);
	}
	
	/**
	 * 资料介绍
	 */
	public java.lang.String getInformation() {
		return getStr("information");
	}
	
	/**
	 * 所属分组 资料所属的分组id
	 */
	public void setSubsetId(java.math.BigInteger subsetId) {
		set("subset_id", subsetId);
	}
	
	/**
	 * 所属分组 资料所属的分组id
	 */
	public java.math.BigInteger getSubsetId() {
		return get("subset_id");
	}
	
}

