package org.project.agenda.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompetition<M extends BaseCompetition<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 竞赛名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 竞赛名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 竞赛链接 竞赛的官网链接,报名链接等
	 */
	public void setLink(java.lang.String link) {
		set("link", link);
	}
	
	/**
	 * 竞赛链接 竞赛的官网链接,报名链接等
	 */
	public java.lang.String getLink() {
		return getStr("link");
	}
	
	/**
	 * 竞赛介绍 可以尝试爬虫获取,也可以手动填写
	 */
	public void setInformation(java.lang.String information) {
		set("information", information);
	}
	
	/**
	 * 竞赛介绍 可以尝试爬虫获取,也可以手动填写
	 */
	public java.lang.String getInformation() {
		return getStr("information");
	}
	
	/**
	 * 竞赛状态 0-报名进行中 1-报名已结束
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 竞赛状态 0-报名进行中 1-报名已结束
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
}

